apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: retail-store-cert
  namespace: retail-store-ns
spec:
  secretName: retail-store-domain-tls-cert # Matches the Gateway's certificateRefs
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: retail-store.zohaibofficial.online
  dnsNames:
  - retail-store.zohaibofficial.online