apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: retail-store-http-redirect
  namespace: retail-store-ns
spec:
  parentRefs:
  - name: retail-store-gateway
    sectionName: http # Attach to HTTP listener
  hostnames:
  - "retail-store.zohaibofficial.online"
  rules:
  - filters:
    - type: RequestRedirect
      requestRedirect:
        scheme: https
        statusCode: 301
        port: 443
